<a href="https://colab.research.google.com/github/ShlokAsthana73/NNA/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install torch torchvision torchaudio

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)

2.8.0+cu126


In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
ten = torch.tensor([[[1,2,3],
                     [4,5,6],
                     [7,8,9]]])
ten

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
ten.ndim

3

In [15]:
ten.shape

torch.Size([1, 3, 3])

In [16]:
ran = torch.rand(3,4)
ran

tensor([[0.2336, 0.1356, 0.4512, 0.6024],
        [0.3415, 0.1165, 0.4381, 0.7359],
        [0.9191, 0.9557, 0.0025, 0.0570]])

In [17]:
torch.rand(3,3)

tensor([[0.8050, 0.6520, 0.7783],
        [0.2926, 0.7890, 0.0797],
        [0.8660, 0.4465, 0.0248]])

In [18]:
torch.zeros(size=(3,4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
one =torch.ones(size=(3,4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
one.dtype

torch.float32

In [21]:
torch.arange(0,10)

/tmp/ipython-input-497691777.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
one_2_ten = torch.arange(start=1,end=11,step=1)
one_2_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
ten_zero = torch.zeros_like(input = one_2_ten)

In [24]:
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [26]:
a+10

tensor([11, 12, 13])

In [27]:
a*10

tensor([10, 20, 30])

In [28]:
a-10

tensor([-9, -8, -7])

In [29]:
a.mul(10)

tensor([10, 20, 30])

In [30]:
a.add(10)

tensor([11, 12, 13])

In [31]:
a.sub(1)

tensor([0, 1, 2])

In [32]:
torch.mul(a,10)

tensor([10, 20, 30])

In [33]:
torch.add(a,10)

tensor([11, 12, 13])

In [34]:
torch.sub(a,1)

tensor([0, 1, 2])

In [35]:
mat1 = torch.rand(3, 2)
mat2 = torch.rand(3, 3)
result = torch.matmul(mat1.T, mat2)
print(result.shape)

torch.Size([2, 3])


In [36]:
torch.matmul(torch.rand(2,3),torch.rand(3,2))

tensor([[0.9451, 1.2836],
        [0.7324, 1.1952]])

In [37]:
torch.matmul(torch.rand(3,2),torch.rand(2,3))

tensor([[0.3145, 0.5558, 0.6988],
        [0.1941, 0.7847, 0.7515],
        [0.1210, 0.6792, 0.6063]])

In [38]:
# tensor aggregation (max . min , sum , mean etc)

In [39]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
torch.min(x)

tensor(0)

In [41]:
x.min()

tensor(0)

In [42]:
torch.max(x)

tensor(90)

In [43]:
x.max()

tensor(90)

In [44]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [45]:
x.type(torch.float32).mean()

tensor(45.)

In [46]:
x.sum()

tensor(450)

In [47]:
x.argmax()

tensor(9)

In [48]:
x[9]

tensor(90)

In [49]:
x=torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [50]:
x_reshape = x.reshape(1,9)

In [51]:
x_reshape,x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [53]:
z[:0]= 5
z , x

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [54]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [55]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [56]:
x_reshape.shape

torch.Size([1, 9])

In [57]:
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])